### ISSUE TITLE
Am I one of the Contributors?

### ISSUE THREAD

**Issue by BardurArantsson** [ygrek/ocaml-extlib#1]
Look, I don't want to be an a-hole, but I do think I do derserve a mention in the README as a "Contributor" since I wrote the whole of the option parsing code. Show a little love? ;)

**Comment by BardurArantsson** [comment]
(I'm not sure where you got the README from... did you write it up by yourself?)

**Comment by ygrek** [comment]
Thanks for the heads up. What email should I put in? Or you can just share a patch.
README is from svn since 2003, I did small changes there to keep it updated.

**Comment by BardurArantsson** [comment]
bardur@scientician.net would be fine. Thanks!
