### ISSUE TITLE
1.7.0 fails to build on Debian Sid

### ISSUE THREAD

**Issue by josch** [ygrek/ocaml-extlib#33]
Hi,

I carry out the following steps in a clean Debian Sid chroot:

    $ wget https://github.com/ygrek/ocaml-extlib/archive/1.7.0.tar.gz
    $ tar xf 1.7.0.tar.gz
    $ cd ocaml-extlib-1.7.0/
    $ apt-get install --no-install-recommends ocaml-nox cppo ocaml-findlib build-essential
    $ make minimal=1 build

And I get from the last command:

    make: git: Command not found
    make -C src build
    make[1]: Entering directory '/tmp/ocaml-extlib-1.7.0/src'
    cppo -D OCAML4   -D WITH_BYTES extBytes.mlpp -o extBytes.ml
    ocamlfind ocamlc -g -package bytes -i extBytes.ml > extBytes.mli
    File "extBytes.mlpp", line 2, characters 15-20:
    Error: Unbound module Bytes
    Makefile:48: recipe for target 'extBytes.mli' failed
    make[1]: *** [extBytes.mli] Error 2
    make[1]: Leaving directory '/tmp/ocaml-extlib-1.7.0/src'
    Makefile:13: recipe for target 'build' failed
    make: *** [build] Error 2

This is with ocaml-nox 4.01.0-5, cppo 0.9.3-3 and ocaml-findlib 1.5.5-0+2.

Some more debug output:

    $ ocamlfind list | grep bytes
    bytes               (version: [OCaml strictly before 4.02])
    $ ocamlfind ocamlc -g -package bytes -i extBytes.ml -verbose
    Effective set of compiler predicates: pkg_bytes,autolink,byte
    + ocamlc -g -i -verbose -I /usr/lib/ocaml/bytes extBytes.ml
    File "extBytes.mlpp", line 2, characters 15-20:
    Error: Unbound module Bytes
    ocamlc returned with exit code 2

What else can I try?

Thanks!

cheers, josch

**Comment by ygrek** [comment]
It appears that `bytes.cmi` is in `libfindlib-ocaml-dev` and after installing this package it builds fine. I think `libfindlib-ocaml` should be fixed to install `bytes.cmi` because it is not `cmi` for findlib library but for the compatibility library that ocamlfind is providing..

**Comment by josch** [comment]
Aha! Thanks, then this was indeed a Debian-specific problem. Installing `libfindlib-ocaml-dev` in addition to `ocaml-findlib` fixes the problem. Thanks!
