### ISSUE TITLE
Specify version number in META file

### ISSUE THREAD

**Issue by mehdid** [ygrek/ocaml-extlib#34]
The META file doesn't currently specify the version number. So, software depending on extlib cannot express requirements based on it. Can you please address this issue in the next release?

This was originally submitted as a Debian bugreport [1].

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=789251

**Comment by ygrek** [comment]
afaics both 1.6.1 and 1.7.0 use `ocamlfind -patch-version` to set version in META, and it works as expected when building manually.. Isn't it the case with debian builds?

**Comment by mehdid** [comment]
Hrm. I am confused. You are right:
$ grep version /usr/lib/ocaml/extlib/META
version = "1.7.0"

Sorry for the noise.
