### ISSUE TITLE
src/Makefile race conditions

### ISSUE THREAD

**Issue by vith** [ygrek/ocaml-extlib#35]
Parallel build fails because of dependencies between the modules being built

```
~/code/ocaml-extlib/src/ocaml-extlib-1.7.0/src
❯ make -j4 all
cppo -D OCAML4  -D OCAML4_02  -D WITH_BYTES extBytes.mlpp -o extBytes.ml
ocamlfind ocamlc -g -package bytes -c enum.mli enum.ml
ocamlfind ocamlc -g -package bytes -c bitSet.mli bitSet.ml
ocamlfind ocamlc -g -package bytes -c dynArray.mli dynArray.ml
ocamlfind ocamlc -g -package bytes -c extArray.mli extArray.ml
File "bitSet.mli", line 74, characters 16-26:
Error: Unbound module Enum
File "dynArray.mli", line 115, characters 19-28:
Error: Unbound module Enum
File "extArray.mli", line 103, characters 25-34:
Error: Unbound module Enum
Makefile:40: recipe for target 'bitSet.cmo' failed
make: *** [bitSet.cmo] Error 2
make: *** Waiting for unfinished jobs....
Makefile:40: recipe for target 'dynArray.cmo' failed
make: *** [dynArray.cmo] Error 2
Makefile:40: recipe for target 'extArray.cmo' failed
make: *** [extArray.cmo] Error 2
```

This was being passed automatically for me because of a systemwide setting in Arch Linux I have.

If you can't easily make parallel make work, maybe add the [.NOTPARALLEL pseudo-target](https://www.gnu.org/software/make/manual/html_node/Special-Targets.html#Special-Targets).

For now I will suggest the `!makeflags` option be added to the PKGBUILD file for the [AUR package](https://aur.archlinux.org/packages/ocaml-extlib/) to avoid the problem until it can be resolved here.

**Comment by ygrek** [comment]
It builds very fast, I just disabled parallel run %)
Thanks for bringing this up!
