### ISSUE TITLE
IO.read_bits fails when reading exactly 31 bits

### ISSUE THREAD

**Issue by nadako** [ygrek/ocaml-extlib#50]
IIUC, this should say `>`, not `>=`
https://github.com/ygrek/ocaml-extlib/blob/103ff096ff2c570411fae3b19032f03e2d86fd2b/src/IO.ml#L755

**Comment by ygrek** [comment]
can you provide test case please?

**Comment by nadako** [comment]
That might take a while for me, as I'm not a "real" OCaml user and I only use it within a specific project setup, which is of course embarassing, but still :)

I'm looking into this [issue in the Haxe compiler](https://github.com/HaxeFoundation/haxe/issues/7796) and I figured out that in this particular case we're indeed trying to read exactly 31 bits (which is the maximum possible value for that specific record in the file).

Also, `extlib`'s documentation say that it's gonna error on `n > 31`:

https://github.com/ygrek/ocaml-extlib/blob/103ff096ff2c570411fae3b19032f03e2d86fd2b/src/IO.mli#L321

The `write_bits` counterpart is also allowed to write 31 bits:

https://github.com/ygrek/ocaml-extlib/blob/103ff096ff2c570411fae3b19032f03e2d86fd2b/src/IO.ml#L775

We actually used to have our own copy of the extlib and [we fixed it at some point](https://github.com/HaxeFoundation/ocamllibs/commit/97ddb4d99884042469e34d1be94b3605d51fbf43) and it worked well for years, but then we migrated to opam and unfortunately the bug reappeared. :-)

**Comment by ygrek** [comment]
Should have submitted patch back then! :)
I would gladly apply patch with a test case that exposes problem.

**Comment by nadako** [comment]
ok, not so hard to "set up" after all, it's just `make test`, lol. see #51

**Comment by ygrek** [comment]
https://travis-ci.org/ygrek/ocaml-extlib/jobs/500857614
build fails on 32-bit arch
