### ISSUE TITLE
Standalone optparse or base64 packages?

### ISSUE THREAD

**Issue by timbertson** [ygrek/ocaml-extlib#53]
I depend on `extlib` for its OptParse module. I don't actually use the rest, I sort of ended up in this situation by initially using the copy of Optparse in Batteries, but then replacing Batteries with smaller, more focussed dependencies. OptParse was the only thing I couldn't find a good replacement for in opam.

My trouble is, extlib clashes with newish versions of cohttp (and probably other packages) which depend on the `base64` package, because both that and extlib define a `Base64` module (see my comments in https://github.com/mirage/ocaml-base64/pull/25)

One fix would be to pull out optparse as a separate package. To be honest it seems worthy of its own opam module, but that's presumably a fair bit more maintenance work for you.

It could also possibly be a separate findlib package and still live under the extlib opam package (i.e. `extlib.optparse`), I _think_ that'd fix the name clash.

A third option is to pull out the problematic `optparse.base64` as a sub-package as well / instead, and then nobody would get the clash unless they explicitly use this sub-package. But that would be a breaking change (for build systems, but not ocaml source code).

**Comment by ygrek** [comment]
yet another option is to exclude base64 from minimal=1 extlib build %)
