### ISSUE TITLE
Unable to build with OCaml 5 trunk compiler

### ISSUE THREAD

**Issue by OlivierNicole** [ygrek/ocaml-extlib#60]
I am unable to build this package with a relatively recent trunk, namely `8bfa64651b`. I get the error:
```
File "extArray.ml", line 1:
Error: The implementation extArray.ml
       does not match the interface extArray.cmi:  ...
       The value `make_float' is required but not provided
       File "extArray.mli", line 121, characters 2-37: Expected declaration
       The value `create' is required but not provided
       File "extArray.mli", line 153, characters 2-60: Expected declaration
       In module Array:
       The value `create_matrix' is required but not provided
       File "extArray.mli", line 156, characters 2-56: Expected declaration
make[1]: *** [Makefile:50 : extArray.cmo] Erreur 2
```

## Steps to reproduce

To install the same compiler revision as me—although I don't understand why it should matter:
```
opam switch create testocaml5 --empty
eval $(opam env --switch=testocaml5)
opam repo add alpha git+https://github.com/kit-ty-kate/opam-alpha-repository.git
opam pin add ocaml-variants.5.1.0+8bfa64651b git+https://github.com/ocaml/ocaml#8bfa64651b
```
Then:
```
opam install extlib
```

Looking briefly at the source, I am confused as to how this could have ever worked, since indeed for OCaml ≥ 4.03 the function `make_float` has no implementation. I see that @kit-ty-kate added extlib to the opam alpha repository without mention of this problem, so maybe she will tell me what I'm missing here?

**Comment by kit-ty-kate** [comment]
The package in opam-alpha-repository contains a copy of https://github.com/ygrek/ocaml-extlib/pull/57 which does fix the issue.

**Comment by kit-ty-kate** [comment]
Looking at our CI though, extlib is still broken but the error is different:
```
#=== ERROR while compiling extlib.1.7.8.1~alpha-repo ==========================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-variants.5.0.0+trunk | git+file:///home/opam/alpha
# path                 ~/.opam/5.0/.opam-switch/build/extlib.1.7.8.1~alpha-repo
# command              ~/.opam/opam-init/hooks/sandbox.sh build make minimal=1 test
# exit-code            2
# env-file             ~/.opam/log/extlib-2851-fb5757.env
# output-file          ~/.opam/log/extlib-2851-fb5757.out
### output ###
# fatal: not a git repository: '.git'
# make -C test all run
# make[1]: Entering directory '/home/opam/.opam/5.0/.opam-switch/build/extlib.1.7.8.1~alpha-repo/test'
# make -C ../src all minimal=1
# make[2]: Entering directory '/home/opam/.opam/5.0/.opam-switch/build/extlib.1.7.8.1~alpha-repo/src'
# make[2]: Nothing to be done for 'all'.
# make[2]: Leaving directory '/home/opam/.opam/5.0/.opam-switch/build/extlib.1.7.8.1~alpha-repo/src'
# ocamlfind ocamlc -linkall -linkpkg -package bytes -I ../src extLib.cma util.ml test_BitSet.ml test_Dllist.ml test_DynArray.ml test_ExtArray.ml test_ExtHashtbl.ml test_ExtList.ml test_ExtString.ml test_IO.ml runner.ml -o extlib_test
# File "util.ml", line 32, characters 12-25:
# 32 |   let str = String.create len in
#                  ^^^^^^^^^^^^^
# Error: Unbound value String.create
# make[1]: *** [Makefile:15: all] Error 2
# make[1]: Leaving directory '/home/opam/.opam/5.0/.opam-switch/build/extlib.1.7.8.1~alpha-repo/test'
# make: *** [Makefile:23: test] Error 2
```
I’ll have a look right now

**Comment by kit-ty-kate** [comment]
oh actually it’s just the tests. Compilation works fine.

**Comment by OlivierNicole** [comment]
Indeed it should work, and in fact I am unable to reproduce my own error, since now it works fine. I am tired and must have used the wrong switch or something. Thank you.

**Comment by OlivierNicole** [comment]
I figured it out, without me noticing `extlib` was being downgraded from 1.7.8.1~alpha-repo to 1.7.7-1, because of https://github.com/ocaml/opam/commit/ec90310c457996a53b891f8afbe54274a045c6b0.

So the situation is that opam-client cannot be installed on 5.0. I'm not sure what to change to fix this.

**Comment by kit-ty-kate** [comment]
That would not be because of https://github.com/ocaml/opam/commit/ec90310c457996a53b891f8afbe54274a045c6b0, it only applies to opam master and does the opposite of what you are explaining (this change says opam master **requires** extlib >= 1.7.8)

However to get opam-client on 5.0 pinning opam master works just fine:
```
opam pin add git+https://github.com/ocaml/opam.git
```

**Comment by OlivierNicole** [comment]
Indeed that does the job. Thank you again!
