### ISSUE TITLE
Update documentation to reflect the deprecation of Makefile

### ISSUE THREAD

**Issue by meator** [ygrek/ocaml-extlib#72]
Hi. I am trying to package ocaml-extlib for my distro. I have followed the README.md on building it (which uses `make`), but then I've noticed this: https://github.com/ygrek/ocaml-extlib/blob/master/CHANGES#L10

Also how do you do minimal builds with dune?

**Comment by ygrek** [comment]
i believe i don't :) i use makefile
i will need to revisit this for the next release

**Comment by ygrek** [comment]
`dune` is only building [minimal set](https://github.com/ygrek/ocaml-extlib/blob/3d9caa998545909a412a6112c3ef899b63224211/src/dune#L4), which is recommended
there is no full build with dune and it is not packaged in opam for several years and there were no complains so i hope i can keep only minimal build sometime soon

README [updated](https://github.com/ygrek/ocaml-extlib/commit/3f51a839ade611c98644ef93c00c3603845334e1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R53)

thanks for reminder

**Comment by meator** [comment]
Thanks for clarifying this!

It looks like the Makefile build method is not deprecated. If that is the case, [`CHANGES`](https://github.com/ygrek/ocaml-extlib/blob/master/CHANGES) should be updated and the "deprecated" status of the Makefile should be revoked (maybe in release notes for a new release/for `unreleased`).

If it is deprecated, it should be reflected in the README and the documentation for building ocaml-extlib with `make` should maybe be removed from README.
